spring:
  application:
    name: user
  profiles:
    active: dev
  redis:
    port: 6379
    host: localhost
    password: 123456
  # 时间格式转换
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml




