server:
  port: 9090

config:
  swagger3:
    flag: true

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}

spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lunarleasing?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: hxx11771177
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
    mail:
      host: smtp.qq.com
      username: 2020480337@qq.com
      password: egpgvsyrdvyrfcca
      protocol: smtp
      default-encoding: UTF-8
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            ssl:
              enable: true
    mybatis:
      configuration:
        map-underscore-to-camel-case: true
      # 支付配置
    alipay:
      appId: 9021000135674906
      # 支付宝公钥和私钥
      appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCBaChD9sQ5tOl9pg/hAyCebbgSv+Lm7tNAonrsAPLvNSrVzTbeT299AY3AAV7s9foq3DX2Q/Nbv0JL7E0oOJ/qFtN2dBOC3E2DPZur5/jWBQGPL+lvm3c+Bsl38YBZE4jzVGgczw/6MTIZbKq7LdkZy46iJZBz3EHFD8Twf4sNrZww9Ce5xey41PEIUdzVdSojNFeUDEq8/AajIlGK71JmK2cF2dKPrpOb4SKCiZU6zSt/QRx29IX6bm1J2nNY/RG2P2FAy8q4pvV3Jsc7sx3eZ7U9pJJ6IOPAu8mhF1uV1UUSip+Xee6RlCHZeNyxgh+ZbQAnSBw91rBY8PaFhhddAgMBAAECggEAEhvUPqaCkRy66+VYJYG9h84Myzrk8rILB+l00B/V3xmOk/qyqetty41zG6JVeU12o5bLSln57SXXji5UIcPCxQxKrTHTJSXVBv+RED5W+QQcUsA+p2qXBiwG92zpLA3qxTpTk2x6bOWDgEFPpv/keJKetBwTmdMBtSTex1ThzZkBhNWq0cou/qmL/ix3p0xKzd9n1e7c0Wef1XiGD8bHMlq1uw6Ct0BsVRNIEwo9GgwSlH9/yG1pxCrMgllz2GlykTseUNAVdJZk0McJZn0HpZVg2Qmzmx3PGKT9/lnSi4VAhbzNYXPoyWi4HK/jzLJ1rBMGxfjiZXOHlh13y0Z31QKBgQDN9ZeonNKML1JCzWPMB+QLAB0f+vPdnvq0q2e1qYztJbrbfP7dczSBnmcnzkOHRWaD0B1axosjd72s0RU4wq7SZjd6DLX3ED1QlBO5FQ6ImlKLQDIZodzXtlVv6cVrw3mfTmePz28cF3WBfrLOmbolClqP9HcjlVd8N7IwlqApJwKBgQCg2Rk7tztRVAo2itzuZDh92E2S84uidBuUptoUxJTdawoDp8cBWCAWP0C5Lk4lSWrhZP9nlaL3VQj/TV13f9rEcZ7Kl+w6MgiFD2f3Bf/UlftcAByP/ZpvZu64h9fmPNP0vEGRhNhRpQmQizuA/68f+gwT/5Nay3KHkzBfPpXl2wKBgGpLKKUlomgk+ABv/eRL4j5nJaDepEMpjFv35kNUKN4vTbt/TA3AKkYHGVfq1OEYSSsYGj5CH4cDgkmRcrFjkFQX2uPLcZH7uJlAgtlPa7vGYXlqfTDLX62YdYmXjYLrVHaKQVpwBPjrhoJ5gBCuN+pr6IdI9L/RkGAUYos/AZObAoGAArlqmf5SfOAlhCL59vevlUISnkiNtuSsiuoAi5WAx/dGJiWzUyyA7p+HoxtLq4oAy2yAfuqj5fiEvH489QcvV2BtRhUopRuv1UEbi62IVbtslHRUB4ROF1Dw/iMe3wFsvZpqqeJMH6Xh8ZbKHTc3ah08EyKjBkin2e/+Q761nz0CgYBwyCk0/frIEN16Q0VrbElm4kCBNB+Pc2NKMPlxz9DlthXD9MfLUz7OuBPvLdyFICQ+QgoXpUo67nMeW8Lu/BxAVdNs0QexYlHlgM20akL/zfBJL7Qh0yZevQb9BU93bYLe/tQubjlRiaOYnf8LuxN6AYHpAJofKHFGslsW5MeesQ==
      alipayPublicKey=: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwJazCO/g9uSdiyml6aQBSHzTh7MAJeOhfGSuqQamwbCAj9JvgH/S+SwROYmMzq5aKyrR3MvdsOwJ1/Zg6MJKbasfH3KhpkCV3Uvsv2CNHNQ4WO6LrNQn7yQr4wzGmj+VU5dPkemjeUoSIDAvl0kEF1yjccg08s20W/BbSjB5Wnt+KmbDYJA+W6inZ9ejFtLBFonJ/D6y6TqQIIatQ3DXJNxMSzR/R6vvobRxY9i6ojY7jxThNL5Nv1YS85WgqlioYt+p26bIMIVbxgBwd2U/oJwkvz1NGjp5wlrEqQXyfUp6oiuzXT4qCtKadMsCBlHECYVZZiAlC6aClZb/usyyQIDAQAB
      # 字符设置
      charset: UTF-8
      # 格式
      format: JSON
      # 网关url和自己对应上图的一致
      gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
      # 签名类型
      signType: RSA2
      # 支付成功的重定向与接口回调 跳转至支付成功页面
      #跳前端支付完成页面
      returnUrl: http://localhost:8081/#/index
      notifyUrl: http://95scdh.natappfree.cc/notify

#app:
#  domain: localhost
#  # 默认上传根路径
#  upload-base-path: D:\website\rentx\upload
#  # 图片访问根路径
#  upload-base-url: /upload/
#  # 图片前缀
#  image-url-prefix: /public/upload
#  jwt:
#    subject: rentx
#    secret: SXWYQjjNgLiLgcMrDZseIEvwbbdGmstBGBgmWFDFUPVXmBqzSDKjfczlQYgvRJoT
#    # 48小时 8 * 3600 * 1000
#    life: 172800000

