spring:
  application:
    name: manager
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      location: /tmp/${spring.application.name}/upload
      max-file-size: 100MB
      max-request-size: 1000MB
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    settings:
      number_format: 0.##
      template_update_delay: 0
      template_exception_handler: cn.jzcscw.base.server.web.FreemakerExceptionHandler
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml



